# Generated by Django 5.1.3 on 2024-11-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_created_at_sale_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('join_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
    ]
